obsidian-path: '/home/b/MEGA/Obsidian/Zettelkasten'
obsidian-file: 'thesis expose 3rd draft.md'
output-path: 'output'
output-tex: 'expose.tex'
output-bibliography: 'bibliography.tex'
output-glossary: 'glossary.tex'
